from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "e2e/selection.spec.ts"
content = PATH.read_text()
old = """test('select all and a bulk mutation remain usable with 500 notes', async ({ page }) => {\n  test.setTimeout(60_000);\n  await page.goto('./');\n  await page.evaluate(async () => {\n    const dbModule = await import('/notes/src/db/index.ts');\n    const base = Date.now();\n    await dbModule.notesDatabase.notes.bulkAdd(\n      Array.from({ length: 500 }, (_, index) => ({\n        id: crypto.randomUUID(),\n        type: 'text' as const,\n        title: `Stress ${index + 1}`,\n        content: `Bulk selection stress note ${index + 1}`,\n        color: 'default' as const,\n        createdAt: base + index,\n        updatedAt: base + index,\n        pinnedAt: null,\n        archivedAt: null,\n        trashedAt: null,\n        position: index,\n        revision: 1,\n      })),\n    );\n  });\n  await page.reload();\n  await expect(page.locator('[data-note-card]')).toHaveCount(500);\n\n  await selectAllVisible(page);\n  const toolbar = page.getByRole('toolbar', { name: 'Selected notes actions' });\n  await expect(toolbar).toContainText('500 selected');\n  await toolbar.getByRole('button', { name: 'Change color for selected notes' }).click();\n  await page\n    .getByRole('dialog', { name: 'Bulk note color' })\n    .getByRole('button', { name: 'Set Gray color on selected notes' })\n    .click();\n\n  await expect(page.locator('[data-note-card][data-color=\"gray\"]')).toHaveCount(500);\n  const grayCount = await page.evaluate(async () => {\n    const dbModule = await import('/notes/src/db/index.ts');\n    return (await dbModule.notesDatabase.notes.toArray()).filter((note) => note.color === 'gray')\n      .length;\n  });\n  expect(grayCount).toBe(500);\n\n  await toolbar.getByRole('button', { name: 'Exit selection' }).click();\n  await expect(page.getByRole('toolbar', { name: 'Selected notes actions' })).toHaveCount(0);\n});\n"""
new = """test('select all and a bulk mutation span 500 notes with progressive card mounting', async ({\n  page,\n}) => {\n  test.setTimeout(60_000);\n  await page.goto('./');\n  await page.evaluate(async () => {\n    const dbModule = await import('/notes/src/db/index.ts');\n    const base = Date.now();\n    await dbModule.notesDatabase.notes.bulkAdd(\n      Array.from({ length: 500 }, (_, index) => ({\n        id: crypto.randomUUID(),\n        type: 'text' as const,\n        title: `Stress ${index + 1}`,\n        content: `Bulk selection stress note ${index + 1}`,\n        color: 'default' as const,\n        createdAt: base + index,\n        updatedAt: base + index,\n        pinnedAt: null,\n        archivedAt: null,\n        trashedAt: null,\n        position: index,\n        revision: 1,\n      })),\n    );\n  });\n  await page.reload();\n\n  const cards = page.locator('[data-note-card]');\n  await expect(cards.first()).toBeVisible();\n  expect(await cards.count()).toBeLessThan(500);\n  await expect(page.locator('.note-grid').first()).toHaveAttribute('data-total-count', '500');\n\n  await selectAllVisible(page);\n  const toolbar = page.getByRole('toolbar', { name: 'Selected notes actions' });\n  await expect(toolbar).toContainText('500 selected');\n  await toolbar.getByRole('button', { name: 'Change color for selected notes' }).click();\n  await page\n    .getByRole('dialog', { name: 'Bulk note color' })\n    .getByRole('button', { name: 'Set Gray color on selected notes' })\n    .click();\n\n  await expect(cards.first()).toHaveAttribute('data-color', 'gray');\n  const grayCount = await page.evaluate(async () => {\n    const dbModule = await import('/notes/src/db/index.ts');\n    return (await dbModule.notesDatabase.notes.toArray()).filter((note) => note.color === 'gray')\n      .length;\n  });\n  expect(grayCount).toBe(500);\n\n  await toolbar.getByRole('button', { name: 'Exit selection' }).click();\n  await expect(page.getByRole('toolbar', { name: 'Selected notes actions' })).toHaveCount(0);\n});\n"""
if content.count(old) != 1:
    raise RuntimeError("Expected one 500-note selection regression test")
PATH.write_text(content.replace(old, new, 1))
